CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, m INTEGER NOT NULL, t INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS events_t ON events (t);
CREATE TABLE IF NOT EXISTS seen (h TEXT PRIMARY KEY, t INTEGER NOT NULL);
